### ISSUE TITLE
This call is ambiguous between Microsoft.Extensions.DependencyInjection.NodeServicesCollectionExtenstions.AddNodeServices and MintPlayer.Extensions.DependencyInjection.NodeServicesCollectionExtenstions.AddNodeServices

### ISSUE THREAD

**Issue by JanakPoojary** [MintPlayer/MintPlayer.AspNetCore.SpaServices.Routing#39]
I want to use the **MintPlayer.AspNetCore.SpaServices.NodeServices** in my .Net 6 project.

In the startup.cs file, I want to register this service using `services.AddNodeServices();` in the `ConfigureServices()` method.

The issue is that I am getting an error regarding ambiguous references in `AddNodeServices()` which is understandable as I have both the using statements.

`using Microsoft.Extensions.DependencyInjection;`
`using MintPlayer.Extensions.DependencyInjection;`

I have to add both because I still want to be able to use Microsoft's dependency injection in my project.

Steps to reproduce:
1. Install the MintPlayer.AspNetCore.SpaServices.NodeServices package 
2. In the startup.cs file add `services.AddNodeServices()` in `ConfigureServices()` method.
3. Add both the using statements `using Microsoft.Extensions.DependencyInjection;` and `using MintPlayer.Extensions.DependencyInjection;`

**Comment by PieterjanDeClippel** [comment]
@JanakPoojary 

I assume you mean you installed the `MintPlayer.AspNetCore.NodeServices` package.

However sadly I can't reproduce what you're experiencing. There seems to be only 1 extension method called `AddNodeServices` available, which is the one provided by this library.

However, nothing prevents you from calling the extension method **not like an extension method**. So instead of

    builder.Services.AddNodeServices();

you can write

    MintPlayer.Extensions.DependencyInjection.NodeServicesServiceCollectionExtensions.AddNodeServices(builder.Services);

Optionally you could share more information:
1) Comment out `MintPlayer.Extensions.DependencyInjection`, just to find out where the other `AddNodeServices` extension method comes from
2) The error should temporarily disappear
3) <kbd>ctrl</kbd> click the `AddNodeServices`. Take a look at the file. Share the assembly with me. The assembly is here:

![image](https://user-images.githubusercontent.com/9629574/218184741-d6733b7b-27e5-4e16-8a3a-cee32a9d7291.png)

**Comment by JanakPoojary** [comment]
Thank you for the reply.
I was not aware about the alternate way of calling an extension method at the time I raised this issue but found that out after couple of days.
So I did exactly what you have mentioned in your comment and it works. You can close the issue.
